<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerB8Ml5Ud\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerB8Ml5Ud/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerB8Ml5Ud.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerB8Ml5Ud\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerB8Ml5Ud\App_KernelDevDebugContainer([
    'container.build_hash' => 'B8Ml5Ud',
    'container.build_id' => '34b1ba7c',
    'container.build_time' => 1635715140,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerB8Ml5Ud');
